insert into tblEmployee (Employee_Name, Employee_Surname, Employee_Cell, Employee_Email, Employee_Role) values ('Tamson', 'Raheal', '536-832-0683', 'traheal@businessweek.com', 'CEO');
insert into tblEmployee (Employee_Name, Employee_Surname, Employee_Cell, Employee_Email, Employee_Role) values ('Omar', 'Piggford', '921-386-0465', 'opiggford1@ask.com', 'Receptionist');
insert into tblEmployee (Employee_Name, Employee_Surname, Employee_Cell, Employee_Email, Employee_Role) values ('Urbain', 'Conrart', '897-131-0513', 'uconrart2@live.com', 'Advertising');
insert into tblEmployee (Employee_Name, Employee_Surname, Employee_Cell, Employee_Email, Employee_Role) values ('Nari', 'Tredger', '206-543-7423', 'ntredger3@1und1.de', 'Organizer');
insert into tblEmployee (Employee_Name, Employee_Surname, Employee_Cell, Employee_Email, Employee_Role) values ('Orson', 'Southerill', '160-545-1254', 'osoutherill4@issuu.com', 'Event Helper');
insert into tblEmployee (Employee_Name, Employee_Surname, Employee_Cell, Employee_Email, Employee_Role) values ('Tomas', 'Test', '518-251-7912', 'ttest0@usa.gov', 'Event Helper');
insert into tblEmployee (Employee_Name, Employee_Surname, Employee_Cell, Employee_Email, Employee_Role) values ('Myer', 'Piperley', '171-638-5477', 'mpiperley1@nifty.com', 'Event Helper');
insert into tblEmployee (Employee_Name, Employee_Surname, Employee_Cell, Employee_Email, Employee_Role) values ('Abramo', 'Ripping', '832-797-9089', 'aripping2@example.com', 'Event Helper');
insert into tblEmployee (Employee_Name, Employee_Surname, Employee_Cell, Employee_Email, Employee_Role) values ('Jacklin', 'Prestedge', '514-129-7523', 'jprestedge3@theglobeandmail.com', 'Event Helper');
insert into tblEmployee (Employee_Name, Employee_Surname, Employee_Cell, Employee_Email, Employee_Role) values ('Even', 'Oselton', '833-260-2097', 'eoselton4@plala.or.jp', 'Manager');
insert into tblEmployee (Employee_Name, Employee_Surname, Employee_Cell, Employee_Email, Employee_Role) values ('Druci', 'Paroni', '793-498-9557', 'dparoni5@yahoo.co.jp', 'Advertising');
insert into tblEmployee (Employee_Name, Employee_Surname, Employee_Cell, Employee_Email, Employee_Role) values ('Koralle', 'Burchell', '383-565-8970', 'kburchell6@lulu.com', 'Organizer Manager');
insert into tblEmployee (Employee_Name, Employee_Surname, Employee_Cell, Employee_Email, Employee_Role) values ('Rolf', 'Ryder', '913-763-8990', 'rryder7@narod.ru', 'Organizer');
insert into tblEmployee (Employee_Name, Employee_Surname, Employee_Cell, Employee_Email, Employee_Role) values ('Deena', 'Quipp', '325-526-2273', 'dquipp8@wired.com', 'Organizer');
insert into tblEmployee (Employee_Name, Employee_Surname, Employee_Cell, Employee_Email, Employee_Role) values ('Marie-ann', 'Mealham', '202-373-8829', 'mmealham9@state.gov', 'Sales Manager');
insert into tblEmployee (Employee_Name, Employee_Surname, Employee_Cell, Employee_Email, Employee_Role) values ('Ally', 'Twitchings', '289-843-6552', 'atwitchingsa@arstechnica.com', 'Sales');
insert into tblEmployee (Employee_Name, Employee_Surname, Employee_Cell, Employee_Email, Employee_Role) values ('Raphaela', 'Arrighi', '891-372-3775', 'rarrighib@si.edu', 'Sales');
insert into tblEmployee (Employee_Name, Employee_Surname, Employee_Cell, Employee_Email, Employee_Role) values ('Garner', 'Bukowski', '714-482-1652', 'gbukowskic@dailymotion.com', 'Event Manager');
insert into tblEmployee (Employee_Name, Employee_Surname, Employee_Cell, Employee_Email, Employee_Role) values ('Fredi', 'Sinclar', '878-788-6364', 'fsinclard@miitbeian.gov.cn', 'Catering');
insert into tblEmployee (Employee_Name, Employee_Surname, Employee_Cell, Employee_Email, Employee_Role) values ('Quintana', 'Poynzer', '115-294-5717', 'qpoynzere@dmoz.org', 'Human Resources Manager');
insert into tblEmployee (Employee_Name, Employee_Surname, Employee_Cell, Employee_Email, Employee_Role) values ('Janet', 'Scirman', '108-921-8021', 'jscirmanf@topsy.com', 'Human Resources');
insert into tblEmployee (Employee_Name, Employee_Surname, Employee_Cell, Employee_Email, Employee_Role) values ('Mady', 'Rathe', '702-761-0948', 'mratheg@sciencedirect.com', 'Catering');
insert into tblEmployee (Employee_Name, Employee_Surname, Employee_Cell, Employee_Email, Employee_Role) values ('Katee', 'Michie', '978-258-6969', 'kmichieh@boston.com', 'Catering');
insert into tblEmployee (Employee_Name, Employee_Surname, Employee_Cell, Employee_Email, Employee_Role) values ('Mandi', 'Heavens', '799-585-3118', 'mheavensi@bbb.org', 'Catering Manager');
insert into tblEmployee (Employee_Name, Employee_Surname, Employee_Cell, Employee_Email, Employee_Role) values ('Ralf', 'Duling', '104-790-9465', 'rdulingj@tiny.cc', 'Financial Manager');